version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: teachme_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: teachme_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./ui/.env
